apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic
  namespace: petclinic
  labels:
    app: pet-clinic
spec:
  selector:
    matchLabels:
      app: pet-clinic
  replicas: 1
  template:
    metadata:
      labels:
        app: pet-clinic
    spec:
      containers:
      - name: pet-clinic
        image: hgw001468/pet-clinic:4c9b6b8
        imagePullPolicy: Always
        ports:
        - containerPort: 8080          
---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic
  namespace: petclinic
spec:
  type: ClusterIP
  selector:
    app: pet-clinic
  ports:
    - port: 8080
      targetPort: 8080


