apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic
  namespace: petclinic
  labels:
    app: pet-clinic
spec:
  selector:
    matchLabels:
      app: pet-clinic
  replicas: 1
  template:
    metadata:
      labels:
        app: pet-clinic
    spec:
      containers:
        - name: pet-clinic
          image: hgw001468/pet-clinic:ee68d43
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
